/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kependudukan;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Dell
 */
public class Frm_Home extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Home
     */
    public Frm_Home() {
        initComponents();
        Tanggal_sekarang();
        jamDigital();
        tampil_tb_pendudukan();
        tampil_tb_kematian();
        tampil_tb_lahir();
        tampil_tb_pindah();
        tampil_tb_pendatang();
        koneksi();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection konek;
    Statement stat;

    Frm_Home(form_entry_kk aThis, boolean rootPaneCheckingEnabled) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    Frm_Home(form_entry_penduduk1 aThis, boolean rootPaneCheckingEnabled) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Berhasil Koneksi");
        } catch (ClassNotFoundException ex) {
            System.out.println("Gagal Koneksi "+ex);
        }
        String url="jdbc:mysql://localhost:3306/kartukeluarga";
        try {
            konek = DriverManager.getConnection(url, "root", "");
            stat = konek.createStatement();
            System.out.println("Ada Database");
        } catch (SQLException se) {
            System.out.println("Tidak ada database "+se);
        }
    }
    
    //perintah menampilkan tanggal
    public void Tanggal_sekarang(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("dd-MM-yyyy") ;
        lbl_tanggal.setText("Tanggal "+kal.format(sekarang));
    }
    
    // jam digital Konstruktor
    public void jamDigital() {
    // ActionListener untuk Keperluan Timer
    ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilai_jam <= 9) {
          // Tambahkan "0" didepannya
          nol_jam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilai_menit <= 9) {
          // Tambahkan "0" didepannya
          nol_menit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilai_detik <= 9) {
          // Tambahkan "0" didepannya
          nol_detik = "0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        // Menampilkan pada Layar
        lbl_jam.setText("Jam "+jam + ":" + menit + ":" + detik);
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();
  }

    private DefaultTableModel tabmodea;  
    public void tampil_tb_pendudukan(){
        //Object []baris = {"No. KK","NIK","Nama Lengkap","Jenis Kelamin","Status Merital","Tempat Lahir", "Tanggal Lahir","Umur","Pendidikan Terakhir","Pekerjaan", "Status Dalam Keluarga", "RT"};
        Object []baris = {"No. KK","NIK","Daftar Kelahiran","RT"};        
        tabmodea = new DefaultTableModel(null, baris);
        tb_penduduk.setModel(tabmodea);
        Connection con = new koneksi().getConnection();
        try {
         //  String sql = "select * from datapenduduk where statuspenduduk=\"Aktif\" or statuspenduduk=\"\" ";
//           String sql = "select kartukeluarga.nokk,kartukeluarga.namalengkap,lahir.nikbayi,lahir.namabayi,lahir.rt from kartukeluarga inner join lahir on kartukeluarga.nokk=lahir.nokk  order by nokk asc ";
            String sql = "select kartukeluarga.nokk,duduk.nik,\n" +
//"datapenduduk.namalengkap, lahir.namabayi,"
 "duduk.namalengkap,kartukeluarga.rt\n" +
"from duduk\n" +
"LEFT join lahir on duduk.nik=lahir.nik\n" +
"LEFT JOIN kartukeluarga on duduk.nokk=kartukeluarga.nokk\n" +
"LEFT join datapenduduk on duduk.nik=datapenduduk.nik order by nokk asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nokk = hasil.getString("nokk");
                String nik = hasil.getString("nik");
        //        String namabayi = hasil.getString("namabayi");
                String namalengkap = hasil.getString("namalengkap");
                
//                
//                String tempatlahir = hasil.getString("tempatlahir");
//                String tanggallahir = hasil.getString("tanggallahir");
//                String namaibu = hasil.getString("namaibu");
//                String namaayah = hasil.getString("namaayah");
                String rt = hasil.getString("rt");
             //  String[] data = {nokk, nik, namalengkap, jk, statusmerital, tempatlahir, tanggallahir, umur, pendidikanterakhir, pekerjaan, statusdalamkeluarga, rt};
                String[] data = {nokk,nik,namalengkap,rt};
                tabmodea.addRow(data);
            }
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
 
    private DefaultTableModel tabmodelahir; 
    public void tampil_tb_lahir(){
        Object []baris = {"No. KK","NIK","Nama Lengkap","JK","Tempat Lahir","Tanggal Lahir","Nama Ibu","Nama Ayah","RT"};        
        tabmodelahir = new DefaultTableModel(null, baris);
        tb_lahir.setModel(tabmodelahir);
        Connection con = new koneksi().getConnection();
        try {
//            String sql = "select duduk.nokk,duduk.nik,lahir.namabayi,"
//                    + "lahir.jk,lahir.tempatlahir,lahir.tempatlahir,lahir.namaibu,\n" +
//                        "lahir.namaayah,lahir.rt"
//                    + "from duduk\n" +
//                        "left join lahir on lahir.nik= duduk.nik";
            String sql="Select*from lahir";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nokk = hasil.getString("nokk");
                String nik = hasil.getString("nik");
                String namabayi = hasil.getString("namabayi");
                String jk = hasil.getString("jk");
                String tempatlahir = hasil.getString("tempatlahir");
                String tanggallahir = hasil.getString("tanggallahir");
                String namaibu = hasil.getString("namaibu");
                String namaayah = hasil.getString("namaayah");
                String rt = hasil.getString("rt");
                String[] data = {nokk,nik,namabayi,jk,tempatlahir,tanggallahir,namaibu,namaayah,rt};
                tabmodelahir.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private DefaultTableModel tabmodepindah; 
    public void tampil_tb_pindah(){
        Object []baris = {"No. KK","NIK","Nama Lengkap","Jenis Kelamin","Status Merital","Tempat Lahir", "Tanggal Lahir","Umur","Pendidikan Terakhir","Pekerjaan", "Status Dalam Keluarga", "Alamat Baru"};
        tabmodepindah = new DefaultTableModel(null, baris);
        tb_pindah.setModel(tabmodepindah);
        Connection con = new koneksi().getConnection();
        try {
            String sql = "select * from pindah";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nokk = hasil.getString("nokk");
                String nik = hasil.getString("nik");
                String namalengkap = hasil.getString("namalengkap");
                String jk = hasil.getString("jk");
                String statusmerital = hasil.getString("statusmerital");
                String tempatlahir = hasil.getString("tempatlahir");
                String tanggallahir = hasil.getString("tanggallahir");
                String umur = hasil.getString("umur");
                String pendidikanterakhir = hasil.getString("pendidikanterakhir");
                String pekerjaan = hasil.getString("pekerjaan");
                String statusdalamkeluarga = hasil.getString("statusdalamkeluarga");
                String alamatbaru = hasil.getString("alamatbaru");
               // String statuspenduduk = hasil.getString("statuspenduduk");
                String[] data = {nokk, nik, namalengkap, jk, statusmerital, tempatlahir, tanggallahir, umur, pendidikanterakhir, pekerjaan, statusdalamkeluarga, alamatbaru};
                tabmodepindah.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
  
    private DefaultTableModel tabmodependatang; 
    public void tampil_tb_pendatang(){
        Object []baris = {"No. KK","NIK","Nama Lengkap","Jenis Kelamin","Status Merital","Tempat Lahir", "Tanggal Lahir","Umur","Pendidikan Terakhir","Pekerjaan", "Status Dalam Keluarga", "RT"};
        tabmodependatang = new DefaultTableModel(null, baris);
        tb_pendatang.setModel(tabmodependatang);
        Connection con = new koneksi().getConnection();
        try {
            String sql = "select * from pendatang";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nokk = hasil.getString("nokk");
                String nik = hasil.getString("nik");
                String namalengkap = hasil.getString("namalengkap");
                String jk = hasil.getString("jk");
                String statusmerital = hasil.getString("statusmerital");
                String tempatlahir = hasil.getString("tempatlahir");
                String tanggallahir = hasil.getString("tanggallahir");
                String umur = hasil.getString("umur");
                String pendidikanterakhir = hasil.getString("pendidikanterakhir");
                String pekerjaan = hasil.getString("pekerjaan");
                String statusdalamkeluarga = hasil.getString("statusdalamkeluarga");
                String rt = hasil.getString("rt");
               // String statuspenduduk = hasil.getString("statuspenduduk");
                String[] data = {nokk, nik, namalengkap, jk, statusmerital, tempatlahir, tanggallahir, umur, pendidikanterakhir, pekerjaan, statusdalamkeluarga, rt};
                tabmodependatang.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
  
     private DefaultTableModel tabmodear;
    public void pencarian_pendudukan(){
        String cari = txt_cari_pendudukan.getText();
       Object[] Baris={"No. KK","NIK","Nama Lengkap","Pekerjaan","RT"};
       // Object[] Baris={"No. KK"};
        tabmodear = new DefaultTableModel(null, Baris);
        tb_penduduk.setModel(tabmodear);

        java.sql.Connection koneksi = new koneksi().getConnection();
        try{
          String sql="Select * from datapenduduk where nokk like '%"+cari+"%' or nik like '%"+cari+"%' or namalengkap like '%"+cari+"%' or pekerjaan like '%"+cari+"%' order by nokk asc";
    
          //     String sql="Select * from penduduk where nokk like '%"+cari+"%' or nik like '%"+cari+"%' or namalengkap like '%"+cari+"%' or jk like '%"+cari+"%' or ttl like '%"+cari+"%' or alamat like '%"+cari+"%' or statuskeluarga like '%"+cari+"%' or namaibu like '%"+cari+"%' or rt like '%"+cari+"%' order by nokk asc";
            java.sql.Statement stmt=koneksi.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                String nokk = rslt.getString("nokk");
                String nik = rslt.getString("nik");
                String namalengkap = rslt.getString("namalengkap");
                String pekerjaan = rslt.getString("pekerjaan");
                //String rt = rslt.getString("rt");
                
            //   String[] dataField = {nokk, nik, namalengkap, pekerjaan, rt};
                String[] dataField = {nokk, nik, namalengkap, pekerjaan};
                tabmodear.addRow(dataField);
            }
        } catch(Exception ex){
        }       
    }
    
    private DefaultTableModel tabmodemati;
    public void tampil_tb_kematian(){
        Object []baris = {"No. KK","NIK","Nama Lengkap","Jenis Kelamin","Status Merital","Tempat Lahir", "Tanggal Lahir","Umur","Pendidikan Terakhir","Pekerjaan", "Status Dalam Keluarga", "RT"};
        tabmodemati = new DefaultTableModel(null, baris);
        tb_kematian.setModel(tabmodemati);
        Connection con = new koneksi().getConnection();
        try {
            //String sql = "select * from kematian where statuspenduduk=\"Pasif\"";
            String sql = "select kartukeluarga.nokk,"
                    + "datapenduduk.nik,"
                    + "datapenduduk.namalengkap,"
                    + "datapenduduk.jk,"
                    + "datapenduduk.statusmerital,"
                    + "datapenduduk.tempatlahir,"
                    + "datapenduduk.tanggallahir,"
                    + "datapenduduk.umur,"
                    + "datapenduduk.pendidikan,"
                    + "datapenduduk.pekerjaan,"
                    + "datapenduduk.statusdalamkeluarga,"
                    + "kartukeluarga.rt from kartukeluarga\n" +
"RIGHT join datapenduduk on kartukeluarga.nokk=datapenduduk.nokk\n" +
"\n" +
"where statuspenduduk=\"Pasif\""+
"order by nokk asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nokk = hasil.getString("nokk");
                String nik = hasil.getString("nik");
                String namalengkap = hasil.getString("namalengkap");
                String jk = hasil.getString("jk");
                String statusmerital = hasil.getString("statusmerital");
                String tempatlahir = hasil.getString("tempatlahir");
                String tanggallahir = hasil.getString("tanggallahir");
                String umur = hasil.getString("umur");
                String pendidikanterakhir = hasil.getString("pendidikanterakhir");
                String pekerjaan = hasil.getString("pekerjaan");
                String statusdalamkeluarga = hasil.getString("statusdalamkeluarga");
                String rt = hasil.getString("rt");
               // String statuspenduduk = hasil.getString("statuspenduduk");
                String[] data = {nokk, nik, namalengkap, jk, statusmerital, tempatlahir, tanggallahir, umur, pendidikanterakhir, pekerjaan, statusdalamkeluarga, rt};
                tabmodemati.addRow(data);
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void pencarian_kematian(){
        String cari = txt_cari_kematian.getText();
        Object[] Baris={"nokk","nik","nama","jk","ttl","alamat","statuskeluarga"};
        tabmodemati = new DefaultTableModel(null, Baris);
        tb_kematian.setModel(tabmodemati);

        Connection koneksi = new koneksi().getConnection();
        try{
            String sql="Select * from kematian where nokk like %"+cari+"% or nik like %"+cari+"% or nama like %"+cari+"% or jk like %"+cari+"% or ttl like %"+cari+"% or alamat like %"+cari+"% or statuskeluarga like %"+cari+"% order by nokk asc";
            java.sql.Statement stmt=koneksi.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                String nokk=rslt.getString("nokk");
                String nik=rslt.getString("nik");
                String nama=rslt.getString("nama");
                String jk=rslt.getString("jk");
                String ttl=rslt.getString("ttl");
                String alamat=rslt.getString("alamat");
                String statuskeluarga=rslt.getString("statuskeluarga");
                
                String[] dataField={nokk,nik,nama,jk,ttl,alamat,statuskeluarga};
                tabmodemati.addRow(dataField);
            }
        }
        catch(Exception ex){
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        data_penduduk = new javax.swing.JPanel();
        btn_cari_pendudukan = new javax.swing.JButton();
        txt_cari_pendudukan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penduduk = new javax.swing.JTable();
        Btn_Kelola_Penduduk = new javax.swing.JButton();
        Btn_Refresh = new javax.swing.JButton();
        Btn_cetak_penduduk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_Kelola_Penduduk1 = new javax.swing.JButton();
        data_penduduk_lahir = new javax.swing.JPanel();
        btn_cari_lahir = new javax.swing.JButton();
        txt_cari_lahir = new javax.swing.JTextField();
        Btn_Refresh4 = new javax.swing.JButton();
        Btn_cetak_penduduk4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_lahir = new javax.swing.JTable();
        Btn_Kelola_Penduduk3 = new javax.swing.JButton();
        data_penduduk_mati = new javax.swing.JPanel();
        btn_cari_mati = new javax.swing.JButton();
        txt_cari_kematian = new javax.swing.JTextField();
        Btn_Refresh1 = new javax.swing.JButton();
        Btn_cetak_penduduk1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_kematian = new javax.swing.JTable();
        Btn_Kelola_Penduduk5 = new javax.swing.JButton();
        data_penduduk_pindah = new javax.swing.JPanel();
        btn_cari_pindah = new javax.swing.JButton();
        txt_cari_pindah = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_pindah = new javax.swing.JTable();
        Btn_Refresh2 = new javax.swing.JButton();
        Btn_cetak_penduduk2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        data_penduduk_pendatang = new javax.swing.JPanel();
        btn_cari_pendatang = new javax.swing.JButton();
        txt_cari_pendatang = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_pendatang = new javax.swing.JTable();
        Btn_Refresh3 = new javax.swing.JButton();
        Btn_cetak_penduduk3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Btn_Kelola_Penduduk4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(999, 775));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/perpustakaan sdfsad.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("PhrasticMedium", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("APLIKASI KEPENDUDUKAN");

        jLabel12.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DESA LEBAKSIUH KECAMATAN CIAWIGEBANG");

        jLabel13.setFont(new java.awt.Font("Yu Mincho", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("KODE POS : 45591");

        lbl_jam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_jam.setText("JAM");

        lbl_tanggal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_tanggal.setText("TANGGAL");

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_jam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_tanggal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_jam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_tanggal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 0));

        data_penduduk.setBackground(new java.awt.Color(51, 0, 0));
        data_penduduk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        data_penduduk.setPreferredSize(new java.awt.Dimension(852, 530));

        btn_cari_pendudukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btn_cari_pendudukan.setText("Cari Data Penduduk");
        btn_cari_pendudukan.setBorder(null);
        btn_cari_pendudukan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cari_pendudukan.setMinimumSize(new java.awt.Dimension(111, 33));
        btn_cari_pendudukan.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_cari_pendudukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_pendudukanActionPerformed(evt);
            }
        });

        txt_cari_pendudukan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari_pendudukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_pendudukanActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 402));

        tb_penduduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_penduduk);

        Btn_Kelola_Penduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/file-edit-16x16.png"))); // NOI18N
        Btn_Kelola_Penduduk.setText("Kelola Data Penduduk");
        Btn_Kelola_Penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Kelola_PendudukActionPerformed(evt);
            }
        });

        Btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uparrow2.png"))); // NOI18N
        Btn_Refresh.setText("Refresh Tabel");
        Btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RefreshActionPerformed(evt);
            }
        });

        Btn_cetak_penduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        Btn_cetak_penduduk.setText("Cetak");
        Btn_cetak_penduduk.setMaximumSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk.setMinimumSize(new java.awt.Dimension(166, 25));
        Btn_cetak_penduduk.setPreferredSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cetak_pendudukActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PENDUDUK");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Btn_Kelola_Penduduk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/file-edit-16x16.png"))); // NOI18N
        Btn_Kelola_Penduduk1.setText("Kelola KK");
        Btn_Kelola_Penduduk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Kelola_Penduduk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_pendudukLayout = new javax.swing.GroupLayout(data_penduduk);
        data_penduduk.setLayout(data_pendudukLayout);
        data_pendudukLayout.setHorizontalGroup(
            data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pendudukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_pendudukLayout.createSequentialGroup()
                        .addGroup(data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE)
                            .addGroup(data_pendudukLayout.createSequentialGroup()
                                .addComponent(Btn_cetak_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cari_pendudukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cari_pendudukan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(data_pendudukLayout.createSequentialGroup()
                        .addComponent(Btn_Kelola_Penduduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Kelola_Penduduk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Refresh)
                        .addGap(37, 37, 37))))
        );
        data_pendudukLayout.setVerticalGroup(
            data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_pendudukLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_cetak_penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_pendudukLayout.createSequentialGroup()
                        .addComponent(btn_cari_pendudukan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_pendudukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(data_pendudukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Kelola_Penduduk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Kelola_Penduduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Penduduk ", new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")), data_penduduk); // NOI18N

        data_penduduk_lahir.setBackground(new java.awt.Color(51, 0, 0));
        data_penduduk_lahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        data_penduduk_lahir.setPreferredSize(new java.awt.Dimension(852, 530));

        btn_cari_lahir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btn_cari_lahir.setText("Cari Data Penduduk");
        btn_cari_lahir.setBorder(null);
        btn_cari_lahir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cari_lahir.setMinimumSize(new java.awt.Dimension(111, 33));
        btn_cari_lahir.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_cari_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_lahirActionPerformed(evt);
            }
        });

        txt_cari_lahir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_lahirActionPerformed(evt);
            }
        });

        Btn_Refresh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uparrow2.png"))); // NOI18N
        Btn_Refresh4.setText("Refresh Tabel");
        Btn_Refresh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Refresh4ActionPerformed(evt);
            }
        });

        Btn_cetak_penduduk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        Btn_cetak_penduduk4.setText("Cetak");
        Btn_cetak_penduduk4.setMaximumSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk4.setMinimumSize(new java.awt.Dimension(166, 25));
        Btn_cetak_penduduk4.setPreferredSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cetak_penduduk4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATA KELAHIRAN");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tb_lahir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb_lahir);

        Btn_Kelola_Penduduk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/file-edit-16x16.png"))); // NOI18N
        Btn_Kelola_Penduduk3.setText("Tambah Penduduk Baru");
        Btn_Kelola_Penduduk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Kelola_Penduduk3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_penduduk_lahirLayout = new javax.swing.GroupLayout(data_penduduk_lahir);
        data_penduduk_lahir.setLayout(data_penduduk_lahirLayout);
        data_penduduk_lahirLayout.setHorizontalGroup(
            data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                        .addGroup(data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                                .addComponent(Btn_cetak_penduduk4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cari_lahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cari_lahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_penduduk_lahirLayout.createSequentialGroup()
                        .addComponent(Btn_Kelola_Penduduk3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Refresh4)
                        .addGap(40, 40, 40))))
        );
        data_penduduk_lahirLayout.setVerticalGroup(
            data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_cetak_penduduk4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                        .addComponent(btn_cari_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(data_penduduk_lahirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Btn_Refresh4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(data_penduduk_lahirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Kelola_Penduduk3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Kelahiran Penduduk", new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")), data_penduduk_lahir); // NOI18N

        data_penduduk_mati.setBackground(new java.awt.Color(51, 0, 0));
        data_penduduk_mati.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        data_penduduk_mati.setPreferredSize(new java.awt.Dimension(852, 530));

        btn_cari_mati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btn_cari_mati.setText("Cari Data Penduduk");
        btn_cari_mati.setBorder(null);
        btn_cari_mati.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cari_mati.setMinimumSize(new java.awt.Dimension(111, 33));
        btn_cari_mati.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_cari_mati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_matiActionPerformed(evt);
            }
        });

        txt_cari_kematian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari_kematian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_kematianActionPerformed(evt);
            }
        });

        Btn_Refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uparrow2.png"))); // NOI18N
        Btn_Refresh1.setText("Refresh Tabel");
        Btn_Refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Refresh1ActionPerformed(evt);
            }
        });

        Btn_cetak_penduduk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        Btn_cetak_penduduk1.setText("Cetak");
        Btn_cetak_penduduk1.setMaximumSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk1.setMinimumSize(new java.awt.Dimension(166, 25));
        Btn_cetak_penduduk1.setPreferredSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cetak_penduduk1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA PENDUDUK MATI");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tb_kematian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_kematian);

        Btn_Kelola_Penduduk5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/file-edit-16x16.png"))); // NOI18N
        Btn_Kelola_Penduduk5.setText("Tambah Penduduk Baru");
        Btn_Kelola_Penduduk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Kelola_Penduduk5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_penduduk_matiLayout = new javax.swing.GroupLayout(data_penduduk_mati);
        data_penduduk_mati.setLayout(data_penduduk_matiLayout);
        data_penduduk_matiLayout.setHorizontalGroup(
            data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_matiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_penduduk_matiLayout.createSequentialGroup()
                        .addComponent(Btn_cetak_penduduk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 896, Short.MAX_VALUE)
                        .addGroup(data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cari_kematian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cari_mati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_penduduk_matiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Btn_Kelola_Penduduk5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Refresh1)
                .addGap(54, 54, 54))
        );
        data_penduduk_matiLayout.setVerticalGroup(
            data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_matiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_cetak_penduduk1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_penduduk_matiLayout.createSequentialGroup()
                        .addComponent(btn_cari_mati, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_kematian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(data_penduduk_matiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Kelola_Penduduk5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Penduduk  Mati", new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")), data_penduduk_mati); // NOI18N

        data_penduduk_pindah.setBackground(new java.awt.Color(51, 0, 0));
        data_penduduk_pindah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        data_penduduk_pindah.setPreferredSize(new java.awt.Dimension(852, 530));

        btn_cari_pindah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btn_cari_pindah.setText("Cari Data Penduduk");
        btn_cari_pindah.setBorder(null);
        btn_cari_pindah.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cari_pindah.setMinimumSize(new java.awt.Dimension(111, 33));
        btn_cari_pindah.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_cari_pindah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_pindahActionPerformed(evt);
            }
        });

        txt_cari_pindah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari_pindah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_pindahActionPerformed(evt);
            }
        });

        tb_pindah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_pindah);

        Btn_Refresh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uparrow2.png"))); // NOI18N
        Btn_Refresh2.setText("Refresh Tabel");
        Btn_Refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Refresh2ActionPerformed(evt);
            }
        });

        Btn_cetak_penduduk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        Btn_cetak_penduduk2.setText("Cetak");
        Btn_cetak_penduduk2.setMaximumSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk2.setMinimumSize(new java.awt.Dimension(166, 25));
        Btn_cetak_penduduk2.setPreferredSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cetak_penduduk2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATA PENDUDUK PINDAH");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout data_penduduk_pindahLayout = new javax.swing.GroupLayout(data_penduduk_pindah);
        data_penduduk_pindah.setLayout(data_penduduk_pindahLayout);
        data_penduduk_pindahLayout.setHorizontalGroup(
            data_penduduk_pindahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_pindahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_penduduk_pindahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE)
                    .addGroup(data_penduduk_pindahLayout.createSequentialGroup()
                        .addComponent(Btn_cetak_penduduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(data_penduduk_pindahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cari_pindah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cari_pindah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_penduduk_pindahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn_Refresh2)
                .addGap(45, 45, 45))
        );
        data_penduduk_pindahLayout.setVerticalGroup(
            data_penduduk_pindahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_pindahLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(data_penduduk_pindahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_cetak_penduduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_penduduk_pindahLayout.createSequentialGroup()
                        .addComponent(btn_cari_pindah, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_pindah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Btn_Refresh2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Penduduk Pindah", new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")), data_penduduk_pindah); // NOI18N

        data_penduduk_pendatang.setBackground(new java.awt.Color(51, 0, 0));
        data_penduduk_pendatang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        data_penduduk_pendatang.setPreferredSize(new java.awt.Dimension(852, 530));

        btn_cari_pendatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        btn_cari_pendatang.setText("Cari Data Penduduk");
        btn_cari_pendatang.setBorder(null);
        btn_cari_pendatang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_cari_pendatang.setMinimumSize(new java.awt.Dimension(111, 33));
        btn_cari_pendatang.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_cari_pendatang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_pendatangActionPerformed(evt);
            }
        });

        txt_cari_pendatang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cari_pendatang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cari_pendatangActionPerformed(evt);
            }
        });

        tb_pendatang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tb_pendatang);

        Btn_Refresh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uparrow2.png"))); // NOI18N
        Btn_Refresh3.setText("Refresh Tabel");
        Btn_Refresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Refresh3ActionPerformed(evt);
            }
        });

        Btn_cetak_penduduk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b_print.png"))); // NOI18N
        Btn_cetak_penduduk3.setText("Cetak");
        Btn_cetak_penduduk3.setMaximumSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk3.setMinimumSize(new java.awt.Dimension(166, 25));
        Btn_cetak_penduduk3.setPreferredSize(new java.awt.Dimension(169, 25));
        Btn_cetak_penduduk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cetak_penduduk3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DATA PENDATANG");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Btn_Kelola_Penduduk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/file-edit-16x16.png"))); // NOI18N
        Btn_Kelola_Penduduk4.setText("Tambah Penduduk Baru");
        Btn_Kelola_Penduduk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Kelola_Penduduk4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_penduduk_pendatangLayout = new javax.swing.GroupLayout(data_penduduk_pendatang);
        data_penduduk_pendatang.setLayout(data_penduduk_pendatangLayout);
        data_penduduk_pendatangLayout.setHorizontalGroup(
            data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                        .addGroup(data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE)
                            .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                                .addComponent(Btn_cetak_penduduk3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cari_pendatang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cari_pendatang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_penduduk_pendatangLayout.createSequentialGroup()
                        .addComponent(Btn_Kelola_Penduduk4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Refresh3)
                        .addGap(54, 54, 54))))
        );
        data_penduduk_pendatangLayout.setVerticalGroup(
            data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_cetak_penduduk3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                        .addComponent(btn_cari_pendatang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cari_pendatang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(data_penduduk_pendatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Btn_Refresh3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(data_penduduk_pendatangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Kelola_Penduduk4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Penduduk Pendatang", new javax.swing.ImageIcon(getClass().getResource("/icon/anggota.png")), data_penduduk_pendatang); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_cetak_penduduk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cetak_penduduk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cetak_penduduk3ActionPerformed

    private void Btn_Refresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Refresh3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Refresh3ActionPerformed

    private void txt_cari_pendatangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_pendatangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_pendatangActionPerformed

    private void btn_cari_pendatangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_pendatangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_pendatangActionPerformed

    private void Btn_cetak_penduduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cetak_penduduk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cetak_penduduk2ActionPerformed

    private void Btn_Refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Refresh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Refresh2ActionPerformed

    private void txt_cari_pindahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_pindahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_pindahActionPerformed

    private void btn_cari_pindahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_pindahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_pindahActionPerformed

    private void Btn_cetak_penduduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cetak_penduduk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cetak_penduduk1ActionPerformed

    private void Btn_Refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Refresh1ActionPerformed
        tampil_tb_kematian();        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Refresh1ActionPerformed

    private void txt_cari_kematianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_kematianActionPerformed
        pencarian_kematian();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_kematianActionPerformed

    private void btn_cari_matiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_matiActionPerformed
        pencarian_kematian();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_matiActionPerformed

    private void Btn_cetak_penduduk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cetak_penduduk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cetak_penduduk4ActionPerformed

    private void Btn_Refresh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Refresh4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Refresh4ActionPerformed

    private void txt_cari_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_lahirActionPerformed

    private void btn_cari_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cari_lahirActionPerformed

    private void Btn_Kelola_Penduduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Kelola_Penduduk1ActionPerformed
        new form_entry_kk(this, rootPaneCheckingEnabled).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Kelola_Penduduk1ActionPerformed

    private void Btn_cetak_pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cetak_pendudukActionPerformed
        // TODO add your handling code here:

        String sql = " select kartukeluarga.nokk,\n" +
        "     kartukeluarga.namalengkap,\n" +
        "    \n" +
        "    \n" +
        "     lahir.nikbayi,\n" +
        "     lahir.namabayi,\n" +
        "   \n" +
        "     lahir.`rt`\n" +
        "FROM\n" +
        "     kartukeluarga kartukeluarga INNER JOIN lahir lahir ON kartukeluarga.nokk = lahir.nokk";
        try {
            ResultSet rs = stat.executeQuery(sql);
            JasperPrint jasperPrint;
            JRResultSetDataSource jrRS = new JRResultSetDataSource (rs);
            JasperReport jasperReport = JasperCompileManager.compileReport("./src/laporan/ok.jrxml");
            jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);

            stat.close();
            konek.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Laporan gak ada "+e);
        }
    }//GEN-LAST:event_Btn_cetak_pendudukActionPerformed

    private void Btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RefreshActionPerformed
        // TODO add your handling code here:
        tampil_tb_pendudukan();
    }//GEN-LAST:event_Btn_RefreshActionPerformed

    private void Btn_Kelola_PendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Kelola_PendudukActionPerformed
        new form_entry_penduduk1(this, rootPaneCheckingEnabled).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Kelola_PendudukActionPerformed

    private void btn_cari_pendudukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_pendudukanActionPerformed
        // TODO add your handling code here:
        pencarian_pendudukan();
    }//GEN-LAST:event_btn_cari_pendudukanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Login().show();
this.dispose();    
//new Login(this, rootPaneCheckingEnabled).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Btn_Kelola_Penduduk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Kelola_Penduduk3ActionPerformed
new form_entry_kelahiran(this, rootPaneCheckingEnabled).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Kelola_Penduduk3ActionPerformed

    private void Btn_Kelola_Penduduk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Kelola_Penduduk4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Kelola_Penduduk4ActionPerformed

    private void Btn_Kelola_Penduduk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Kelola_Penduduk5ActionPerformed
    new form_entry_kk(this, rootPaneCheckingEnabled).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Kelola_Penduduk5ActionPerformed

    private void txt_cari_pendudukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cari_pendudukanActionPerformed
pencarian_pendudukan();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cari_pendudukanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Kelola_Penduduk;
    private javax.swing.JButton Btn_Kelola_Penduduk1;
    private javax.swing.JButton Btn_Kelola_Penduduk3;
    private javax.swing.JButton Btn_Kelola_Penduduk4;
    private javax.swing.JButton Btn_Kelola_Penduduk5;
    private javax.swing.JButton Btn_Refresh;
    private javax.swing.JButton Btn_Refresh1;
    private javax.swing.JButton Btn_Refresh2;
    private javax.swing.JButton Btn_Refresh3;
    private javax.swing.JButton Btn_Refresh4;
    private javax.swing.JButton Btn_cetak_penduduk;
    private javax.swing.JButton Btn_cetak_penduduk1;
    private javax.swing.JButton Btn_cetak_penduduk2;
    private javax.swing.JButton Btn_cetak_penduduk3;
    private javax.swing.JButton Btn_cetak_penduduk4;
    private javax.swing.JButton btn_cari_lahir;
    private javax.swing.JButton btn_cari_mati;
    private javax.swing.JButton btn_cari_pendatang;
    private javax.swing.JButton btn_cari_pendudukan;
    private javax.swing.JButton btn_cari_pindah;
    private javax.swing.JPanel data_penduduk;
    private javax.swing.JPanel data_penduduk_lahir;
    private javax.swing.JPanel data_penduduk_mati;
    private javax.swing.JPanel data_penduduk_pendatang;
    private javax.swing.JPanel data_penduduk_pindah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JTable tb_kematian;
    private javax.swing.JTable tb_lahir;
    private javax.swing.JTable tb_pendatang;
    private javax.swing.JTable tb_penduduk;
    private javax.swing.JTable tb_pindah;
    private javax.swing.JTextField txt_cari_kematian;
    private javax.swing.JTextField txt_cari_lahir;
    private javax.swing.JTextField txt_cari_pendatang;
    private javax.swing.JTextField txt_cari_pendudukan;
    private javax.swing.JTextField txt_cari_pindah;
    // End of variables declaration//GEN-END:variables
}
